services:
  - type: web
    name: codeleap-backend-api
    runtime: python
    buildCommand: "./manage.py migrate"
    startCommand: "gunicorn codeleap_backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ""
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: codeleap-backend-api-oxdh.onrender.com
